### PR TITLE
Average goals per game

### PR DESCRIPTION
**Pull request by ejdesh**

### CODE REVIEW

**Review by Crosswolfv1 — APPROVED** [review]
I have reviewed your code it does use the .to_i that we discussed in the study hall, before merging want to address variable types tmr in DSU, otherwise approved on my end

**Comment by Paul-Knapp** [comment]
looks good thanks for matching formatting to the new test structure.

**Review by Crosswolfv1 — APPROVED** [review]
Changes are good, I approve for merge

**Review by wally-yawn — APPROVED** [review]
Reviewed these changes in huddle and they look good.

**Pull request merged**
