### PR TITLE
Accurate teams

### PR DESCRIPTION
**Pull request by Montana-Pfeifer**
added 
#team_shot_goal_ratios
#most_accurate_team
#least_accurate_team

should be able to input methods and get a return of team name as a string

### CODE REVIEW

**Review by Crosswolfv1 — CHANGES_REQUESTED** [review]
Need to include the ability to check by a specific season, should be able to mirror the refactored coaches code for the main and helper methods

**Review by wally-yawn — CHANGES_REQUESTED** [review]
I think you deleted the entire stat_tracker class...

**Review by Crosswolfv1 — APPROVED** [review]
Changes are good, removed random tabs and spaces in stat_tracker

Thank you for making a season operator in the helper looks good!

**Review by wally-yawn — APPROVED** [review]
Changes look good!

**Pull request merged**
