### PR TITLE
fix: cleaned up get_scores to remove season parameter

### PR DESCRIPTION
**Pull request by ejdesh**
removed season parameter since it is not in game_team csv

### CODE REVIEW

**Comment by Montana-Pfeifer** [comment]
We'll need the seasons because it will show the teams and their goals inside of that season Home or away.

**Comment by wally-yawn** [comment]
It looks like get_scores is using the games.csv which does include the season

**Comment by wally-yawn** [comment]
Discussed my comment in huddle and we're good to move

**Review by wally-yawn — APPROVED** [review]

**Comment by Montana-Pfeifer** [comment]
> We'll need the seasons because it will show the teams and their goals inside of that season Home or away.

resolved all concerns in meeting

**Review by Crosswolfv1 — APPROVED** [review]
Discussed in huddle, changes approved

**Pull request merged**
